### ISSUE TITLE
shift_exceptions does not prevent New Years Day (Observed) in some cases

### ISSUE THREAD

**Issue by paulpharr** [peopledoc/workalendar#610] opened 2021-01-07 19:19 UTC
When January 1 is on a Saturday (as it is in 2022), the United States calendar for the prior year (in this case 2021) has holiday New Years Day (Observed) on December 31 even when shift_exceptions contains an exception for January 1.

work holiday: 2021-12-31 [fri] - New Years Day (Observed)

    shift_exceptions = ((1, 1),
                        (12, 25),
                        )

**Comment by brunobord** [comment] 2021-01-08 15:56
Looks like a duplicate of https://github.com/peopledoc/workalendar/issues/200
I think I need to work on it this year. Stay tuned!

**Closed** 2021-03-05 14:28 UTC
Labels: bug, duplicate

**Comment by brunobord** [comment] 2021-03-05 14:32
you may try to upgrade to the 15.0.2, hopefully, it includes a fix to your issue.

* https://pypi.org/project/workalendar/15.0.2/
* https://github.com/peopledoc/workalendar/releases/tag/15.0.2
